// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Role struct {
	ID   int32
	Name string
}

type User struct {
	ID           int32
	Email        string
	Name         string
	Lastname     string
	PasswordHash []byte
	RoleID       sql.NullInt32
}
